### ISSUE TITLE
[Feature Request] option to change nvngx_dlss.dll version

### ISSUE THREAD

**Issue by SunnyMoo** [SpecialKO/SKIF#19]
Hi,
first thanks a lot for your work on SpecialK, it's awesome !
As title says, do you think it's possible to add an option to SKIF in order to change the nvngx_dlss.dll version used before launching a game ?
Versions you can find on https://www.techpowerup.com/download/nvidia-dlss-dll/
I know I can do it manually by replacing dll file, and already do this way, but it would be nice to be able to swap it directly in SKIF with up to date nvngx_dlss.dll files.
Thank you !

**Comment by marat569** [comment]
I know this isn't an answer to your question, but try this tool out. It's very light weight, easy to use, and great for managing dlss dlls. Both replacing/updating and restoring.

https://beeradmoore.github.io/dlss-swapper/

**Comment by SunnyMoo** [comment]
Sadly this tool is pretty buggy atm, that's why I do it manually.
Adding the option to SKIF is no priority for me but I think it would be a cool addition.
Regards.

**Comment by Aemony** [comment]
This feature is outside of the scope of SKIF, sadly, so will never be implemented (and I'm not even sure we'd be allowed to redistribute all of those DLL files anyway).
