### ISSUE TITLE
Embed licenses in app

### ISSUE THREAD

**Issue by Aemony** [SpecialKO/SKIF#27]
All the FOSS licenses we are using needs to be embedded in the app itself -- perhaps as a "View licenses..." link in the Components section.

Most of them are MIT -- maybe there's an easy way to minimize boilerplate license text for shared licenses?

**Comment by marat569** [comment]
Plenty of space here if you need help finding a spot -- https://i.imgur.com/oFOl1JN.png

You can make it a link that you click, and it opens a separate little window with dropdowns -- that way you dont have to worry about the skif client itself getting "bloated"

Since the licenses will live in their own tiny window, the text from them isn't a big deal -- and can be managed easier

**Comment by Aemony** [comment]
I am planning on having them displayed in a popup like the release notes/changelog, with all licenses listed in one scrollable textfield.

This is why I am probably going to reduce duplicated licenses and just list the copyrights of all MIT licensed code just above the MIT boilerplate, with all the other unique licenses below that.

**Comment by marat569** [comment]
> I am planning on having them displayed in a popup like the release notes/changelog, with all licenses listed in one scrollable textfield.
> 
> This is why I am probably going to reduce duplicated licenses and just list the copyrights of all MIT licensed code just above the MIT boilerplate, with all the other unique licenses below that.

What I had in mind was something similar to reshade's info tab

You'd press a "licenses" link, it would spawn a new window, and that window would have a say "My Imgui" dropdown, click "My Imgui", and it shows all the licenses related to that. 

but in reality a wall of text works fine too, its not like its content people will engage with

**Comment by Aemony** [comment]
I ended up adding a link to the About tab (below Privacy Policy) that opens
https://github.com/SpecialKO/SKIF/blob/master/LICENSE-3RD-PARTY
