### ISSUE TITLE
[Enhancement] Investigate using custom embedded fonts instead

### ISSUE THREAD

**Issue by Aemony** [SpecialKO/SKIF#7]
Currently SKIF defaults to using various default Windows fonts included in the OS, however it might be preferably to move over to using a separate third-party font to ensure a unique typeface across all languages, such as https://fonts.google.com/noto

Might possibly fix SpecialKO/SpecialK#23 as well...?

**Comment by Aemony** [comment]
Too damn much space required for this feature... It's been put on hold for now.

**Comment by ColonelGerdauf** [comment]
It depends on what exactly you want to achieve.

The Brands emoji font I am not too sure about, but a font family I can recommend for readability is the Source family.

**Comment by Aemony** [comment]
As I mentioned the intention is, or at least was, to move over to a single font family to ensure a unique typeface across all languages. The Noto familty (with their "a typeface for the world" tagline) is perfect for this as it contains Latin, Chinese, Japanese, Korean, Vietnamese, and all other character sets around the world in its family, however some of those font files are huge (percentage-wize) and more than double the size SKIF's install size.

**Comment by Aemony** [comment]
Closing this as the feature has sort of been put on the backburner due to the downsides of implementing it.

We'll continue to use native Windows fonts for now.
